use_frameworks!

platform :ios, '9.0'

target 'ZHEverlastingThread_Example' do
  pod 'ZHEverlastingThread', :path => '../'

  target 'ZHEverlastingThread_Tests' do
    inherit! :search_paths

    
  end
end
